# config/moonshine.yml is loaded both by capistrano and moonshine.
#  The result is the values defined here can be used in `config/deploy.rb` directly
#  and in `app/manifest/application_manifest.rb` via `configuration`

# ruby to install at `cap deploy:setup` time. If you change this value, you
# need to run `cap ruby:upgrade`. Currently allowed values include: mri,
# src187, ree, ree187
:ruby: ree187

# Name of your application. Should be something with only alphanumerics, hypens
# and underscores.
:application: redmine

# Deploy user
:user: redmine

# Timezone to set server's time to. Defaults to UTC
#:time_zone: UTC

# Directory where application is deployed to
:deploy_to: /srv/redmine

# Primary domain application will be accessed as 
:domain: ppm.monarchmedia.com

:ssl:
  :self_signed: true
  :only: true

# Domain aliases for application. One common use of this is for asset hosts.
#:domain_aliases:
#  - assets1.yourapp.com
#  - assets2.yourapp.com

# Source control management to use. Defaults to git.
# If you change this value, you will need to run: cap vcs:install
#:scm: git
# Reposistory URI for checking out code at deploy time
:repository: redmine@ppm.monarchmedia.com:/home/redmine/git/redmine.git

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
#:app_symlinks:
#  - system

# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
#:shared_config:
#  - config/database.yml

# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config

# Specify native dependencies of gems. Moonshine comes with some preconfigured
# defaults, but this allows you to add to them. Please file an issue at
# http://github.com/railsmachine/moonshine/issues if there are additional gem
# dependencies Moonshine should know about.
#:apt_gems:
#  :awesomegem:
#    - awesome
#    - libawesome-dev

# Passenger-specific options. Refer to the following templates for details
# about what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.conf.erb 
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.vhost.erb 
:passenger:
  :max_pool_size: 3
  :version: 2.2.9

# MySQL-specific options. Refer to the following templates for details about
# what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/moonshine.cnf.erb 
:mysql:
  :innodb_buffer_pool_size: 128M
  :auto_increment_increment: '1'

:database:
  :production:
    :adapter: mysql
    :host: localhost
    :username: redmine
    :password: 'ppm_redmine_140'
    :database: 'ppm_redmine'
:session_key: '43bc5ce71f2dffaf48082dae8ba5d1a94812011ebf3c68c45d433697c94f61253d64722efb710a56'
:redmine:
  :receive_imap:
    :host: 'imap.gmail.com'
    :port: '993'
    :ssl: '1'
    :username: 'redmine@monarchmedia.com'
    :password: 'ppm71b92be1'
    :minute: '*/15'
    :hour:   '*'
    :month:  '*'
    :extra_options: ""
:redmine_email_yml:
    :production:
      :delivery_method: :async_smtp
      :smtp_settings:
        :enable_starttls_auto: true
        :address: "smtp.gmail.com"
        :port: 587
        :domain: "smtp.gmail.com"
        :authentication: :plain
        :user_name: 'redmine@monarchmedia.com'
        :password: 'ppm71b92be1'
